### ISSUE TITLE
Error reading memcache set with expiry 

### ISSUE THREAD

**Issue by sunilmadan2006** [cnblogs/EnyimMemcachedCore#10]
Error reading memcache with expiry 
i stored/write  memcache with below code but not able to read with key

MemcachedClient.Store(StoreMode.Set, "abc", "10",new TimeSpan(0,23, 0, 0));

I tried with two methods, timespan and datetime

**Comment by cnblogs-dudu** [comment]
Please provide sample code to reproduce this issue.

**Comment by sunilmadan2006** [comment]
public class MemcacheClient
    {
        private static MemcachedClient objMemcachedClient { get; set; }

        public MemcacheClient()
        {
            if (objMemcachedClient == null)
            {
                IConfigurationRoot Configuration = new ConfigurationBuilder().AddJsonFile(System.IO.Path.GetFullPath("appsettings.json"), optional: true, reloadOnChange: true).Build();
                var serviceProvider = new ServiceCollection()
                         .AddLogging().AddOptions().AddEnyimMemcached(options =>
                         {                     
                     Configuration.GetSection("enyimMemcached").Bind(options);
                             options.Protocol = MemcachedProtocol.Text;
                         })
                        .BuildServiceProvider();
                serviceProvider.GetService<ILoggerFactory>().AddConsole(LogLevel.Debug);
                ILogger<MemcachedClient> logger = serviceProvider.GetService<ILoggerFactory>().CreateLogger<MemcachedClient>();
                IMemcachedClientConfiguration objMemcachedClientConfiguration = serviceProvider.GetService<IMemcachedClientConfiguration>();
                objMemcachedClient = new MemcachedClient(logger, objMemcachedClientConfiguration);
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="strCachedKey"></param>
        /// <param name="objCachedValue"></param>
        /// <param name="tsExpiry"></param>
        /// <returns></returns>
        public bool Write(string strCachedKey, object objCachedValue)
        {
            bool result = false;
            try
            {
                if (!string.IsNullOrEmpty(strCachedKey))
                {
                    strCachedKey = strCachedKey.Replace(" ", string.Empty);
                    result = objMemcachedClient.Store(StoreMode.Set, strCachedKey, objCachedValue);
                   return result ;
                }                
            }
            catch (Exception exc)
            {
                IOMLogger.LogError(exc, "MemCache_Write && Key: " + strCachedKey);
            }

            return result;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="strCachedKey"></param>
        /// <param name="objCachedValue"></param>
        /// <param name="tsExpiry"></param>
        /// <returns></returns>
        public bool Write(string strCachedKey, object objCachedValue, TimeSpan tsExpiry)
        {
            bool result = false;
            try
            {
                if (!string.IsNullOrEmpty(strCachedKey))
                {
                    strCachedKey = strCachedKey.Replace(" ", string.Empty);
                    result = objMemcachedClient.Store(StoreMode.Set, strCachedKey, objCachedValue, tsExpiry);
                 return result;
                }               
            }
            catch (Exception exc)
            {
                IOMLogger.LogError(exc, "MemCache_Write && Key: " + strCachedKey);
            }

            return result;
        }
		}

when i m calling this via obkect in my controller : it should write memcache key for 10 minutes. But unable to write cache 
bool isWrite = objMemcachedClient.Store(Enyim.Caching.Memcached.StoreMode.Set, "abc", "core memcache write" , new TimeSpan(0,10, 0)); 

but when i m calling without timespan able to write cache

bool isWrite = objMemcachedClient.Store(Enyim.Caching.Memcached.StoreMode.Set, "abc", "core memcache write" );

**Comment by cnblogs-dudu** [comment]
Passed a unit test for this.

**Comment by cnblogs-dudu** [comment]
It can not be reproduced.
