### ISSUE TITLE
Is the socket being reset a cause for concern?

### ISSUE THREAD

**Issue by rgelb** [cnblogs/EnyimMemcachedCore#115]
I have the following in the logs from library:

> Acquiring stream from pool. Unspecified/10.147.36.30:11212
Socket 85062d70-1b4e-4725-81d4-5ab72b0cd5fa was reset
Socket was reset. 85062d70-1b4e-4725-81d4-5ab72b0cd5fa
Releasing socket 85062d70-1b4e-4725-81d4-5ab72b0cd5fa
Are we alive? True

For every hit to memcached I get **socket was reset** Debug level message.  
Is this cause for concern?  Otherwise everything works well.

**Comment by cnblogs-dudu** [comment]
Reset socket is put back into the socket pool to reuse.
