### ISSUE TITLE
Not possible to set custom transcoder?

### ISSUE THREAD

**Issue by nico-francois-vex** [cnblogs/EnyimMemcachedCore#13]
It appears it's not possible to set a custom transcoder.

It looks like this would need to be added to MemcachedClientOptions and then picked up by MemcachedClientConfiguration?

**Comment by nico-francois-vex** [comment]
I had a look at the actual code and got it working with two very simple modifications, see attached zip for a patch file.

Can this be integrated into the next release?

[customtranscoder.zip](https://github.com/cnblogs/EnyimMemcachedCore/files/935629/customtranscoder.zip)

**Comment by cnblogs-dudu** [comment]
Thanks. Included this patch in EnyimMemcachedCore 1.1.1.8.

**Comment by dot-i** [comment]
Excellent! Thanks.
