### ISSUE TITLE
Version 2.1.14 runs fine on aws lambda .netcore 2.1 (linux) but upgrading to 2.4.1 fails.    

### ISSUE THREAD

**Issue by Efrat1234567** [cnblogs/EnyimMemcachedCore#138]
Hi. After upgrading I'm getting the following errors:

System.PlatformNotSupportedException: Sockets on this platform are invalid for use after a failed connection attempt.
at System.Net.Sockets.Socket.ThrowMultiConnectNotSupported()
at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)

My last working version (2.1.14) used " Socket.Connect(IPAddress address, int port)" method.
 
Why was this changed in the newer versions? Are they not compatible with linux?
I have tried all versions after 2.1.14 and all of them is failing on linux with same error.

Is it possible to fix it - to use again the old method but with auto discovery giving only the cluster configuration endpoint?

Thanks,
Efrat.

**Comment by cnblogs-dudu** [comment]
Apply a workaround for this issue in EnyimMemcachedCore 2.4.2.
