### ISSUE TITLE
Disable logging

### ISSUE THREAD

**Issue by cesarbmx** [cnblogs/EnyimMemcachedCore#140]
How can I avoid seeing the below trace in my log? I am using IDistributedCache with default configuration. 
I believed that, by default, the client was coming with logging disabled.

```
Memcached server address - xxxxx:11211
SetAsync("xxxxx")
GetAsync("xxxxx")
MemcachedInitPool-cost: 1182.8034ms
Enyim.Caching.Memcached.Protocol.Binary.GetOperation.ReadResponseAsync result: Not found
SetAsync("xxxxx")
MemcachedInitPool-cost: 1139.559ms
```

**Comment by cnblogs-dudu** [comment]
Change log level in appsettings.json.
```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Warning"
    }
  },

  "Serilog": {
    "MinimumLevel": {
      "Default": "Warning"
    }
  }
}
```

**Comment by cesarbmx** [comment]
Thank you.

I guess these memcached logs come as`LogLevel: Information`
Since I am also logging Information from my application code, what you suggest would also hide my application related logs.
Is there a way to hide Enyim specific logs while keeping `LogLevel: Information` in the appsettings?

**Comment by cnblogs-dudu** [comment]
Use the following log level settings.
```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Warning",
      "Enyim.Caching": "Warning"
    }
  },

  "Serilog": {
    "MinimumLevel": {
      "Default": "Warning",
      "Override": {
        "Enyim.Caching": "Warning"
      }
    }
  }
}
```

**Comment by cesarbmx** [comment]
It worked! Thank you very much.
