### ISSUE TITLE
Unable to fetch Complex object type (List<>), Return unexpected BsonType

### ISSUE THREAD

**Issue by LetMeTryItOut** [cnblogs/EnyimMemcachedCore#149]
Hi Team,

I am facing an issue wherein, the I am trying to set cache via Enyim.Memcached .Net framework assembly and trying to get it via EnyimMemcachedCore assembly.

Before going into the details, I wanted to understand is this achievable. As for primitive data types above scenario works pretty well but not for complex types it won't - for instance: List<>, Dictionary<String, List<>>

Enyim.Memcached version -   2.16.0
EnyimMemcachedCore - 2.4.4, 2.0.0. tried almost 5 of the versions it didn't work
**Version 2.1.11** : As mentioned in one of the previous issue [Issue-79](https://github.com/cnblogs/EnyimMemcachedCore/issues/79) it says that is resolves Unexpected BsonType error, which is exactly the same I am receiving too.

I debug the code of both above assemblies
In Framework: we are using BinaryFomatter while saving and reading for serialization, however
In Core: we are first converting to BsonWriter and then serializing

Is that the case, why the above error keeps on appearing as the formatter is not same.

I am using Memcached exe and using windows service to keep it running. Using default port: 11211, and protocol as binary. No other settings specified.

Below is concrete class object I am using to set and get it in Memcached

Class Employee 
prop string Name
prop string employeeID

Even with single list I am not able to set/get.

Could you please guide me what am I missing here, please feel free to let me know for any further details required.

**Comment by banderberg** [comment]
I have the same issue storing/retrieving IEnumerable of objects.

**Comment by masterbk** [comment]
I have the same issue storing/retrieving Dictionary of objects.

**Comment by cnblogs-dudu** [comment]
Introduced MessagePackTranscoder to support complex object type. Please try [EnyimMemcachedCore 2.6.0-preview1](https://www.nuget.org/packages/EnyimMemcachedCore/2.6.0-preview1)

Add a Transcoder setting to enable MessagePackTranscoder .
```json
{
  "enyimMemcached": {
    "Servers": [
      {
        "Address": "memcached",
        "Port": 11211
      }
    ],
    "Transcoder": "MessagePackTranscoder"
  }
}
````
