### ISSUE TITLE
Missing KeyTransform on store methods

### ISSUE THREAD

**Issue by NooNameR** [cnblogs/EnyimMemcachedCore#17]
Missing KeyTransfrom inside PerformStore / PerformStoreAsync methods

**Comment by NooNameR** [comment]
https://github.com/cnblogs/EnyimMemcachedCore/pull/16

**Comment by cnblogs-dudu** [comment]
Thanks. Published a nuget package EnyimMemcachedCore 1.1.1.11 for this.
