### ISSUE TITLE
IDistributedCache methods swallowing exceptions

### ISSUE THREAD

**Issue by dengber** [cnblogs/EnyimMemcachedCore#175]
For IDistributedCache methods of MemcachedClient class, when operation failed, they return default values.
They should throw exceptions so that the invoker can know operation failed or not.

**Comment by cnblogs-dudu** [comment]
Add SuppressException option in  [EnyimMemcachedCore 2.5.6](https://www.nuget.org/packages/EnyimMemcachedCore/2.5.6) to disable swallowing.
```json
{
  "enyimMemcached": {
    "suppressException": "false"
  }
}
```

**Comment by dengber** [comment]
Thank you for your quickly response!
