### ISSUE TITLE
Address is misspelled in appsettings.json

### ISSUE THREAD

**Issue by greggbjensen** [cnblogs/EnyimMemcachedCore#2]
This is a great library you have put together.  I ran into one minor issue blow, which is that you have to misspell `Addess` to get it to work.

```json
{
  "enyimMemcached": {
    "Servers": [
      {
        "Addess": "memcached",
        "Port": 11211
      }
    ]
  }
}
```

**Comment by greggbjensen** [comment]
I created a pull request to fix this.
#4

**Comment by cnblogs-dudu** [comment]
Sorry for this misspelling.
