### ISSUE TITLE
Doesn't seem to run using .NET Standard 2.0 Preview

### ISSUE THREAD

**Issue by nico-francois-vex** [cnblogs/EnyimMemcachedCore#20]
Hello,

There's a missing method exception when using **EnyimMemcachedCore** together with *2.0.0-preview2-final*:

```
System.MissingMethodException : Method not found: 'System.Threading.Tasks.Task`1<Byte[]> Microsoft.Extensions.Caching.Distributed.IDistributedCache.GetAsync(System.String)'.
```

Any chance this could be fixed?

**Comment by cnblogs-dudu** [comment]
Uploaded a nuget package EnyimMemcachedCore 2.0.0-beta1 for this. See https://www.nuget.org/packages/EnyimMemcachedCore/2.0.0-beta1

**Comment by nico-francois-vex** [comment]
Great, thanks for the quick follow-up!
