### ISSUE TITLE
Stop referencing Microsoft.AspNetCore.Http.Abstractions

### ISSUE THREAD

**Issue by Gonyoda** [cnblogs/EnyimMemcachedCore#203]
We are getting security alerts in our projects using EnyimMemcachedCore due to this library referencing Microsoft.AspNetCore.Http.Abstractions 2.2.0 ([nuget is obsolete](https://www.nuget.org/packages/Microsoft.AspNetCore.Http.Abstractions/)) which references System.Text.Encodings.Web 4.5.0 that has a known vulnerability [here](https://github.com/dotnet/runtime/issues/49377) and [here](https://github.com/dotnet/announcements/issues/178).  

Is there a way to stop referencing this library (does anyone still use EnyimMemcachedApplicationBuilderExtensions.UseEnyimMemcached??) or have different builds for modern .net versions that no longer reference this old package?

**Comment by cnblogs-dudu** [comment]
Relate to https://github.com/cnblogs/EnyimMemcachedCore/pull/172#issuecomment-1525225105 #195

**Comment by Gonyoda** [comment]
TYSM! :)
