### ISSUE TITLE
Object not set to an instance of an object.

### ISSUE THREAD

**Issue by oezoezoe** [cnblogs/EnyimMemcachedCore#221]
![image](https://github.com/cnblogs/EnyimMemcachedCore/assets/5367570/1f82fdc6-38f0-455f-b7d6-85f34078f3b4)

On line 44 of the PooledSocket constructor _endpoint is used, but this value has not been set until line 64,

Pls move line 64 up to like 38 so that _endpoint is set.

**Comment by cnblogs-dudu** [comment]
Fixed in [3.2.1](https://www.nuget.org/packages/EnyimMemcachedCore/3.2.1).
