### ISSUE TITLE
how to configure multi server?

### ISSUE THREAD

**Issue by the404** [cnblogs/EnyimMemcachedCore#27]
I want use this to store data in multi server,but always just store in one

is that need some code to config?

I just add a config in appsettings.json

```
"Memcached": {
    "Servers": [
      {
        "Address": "39.108.125.154",
        "Port": 11211
      },
      {
        "Address": "39.108.125.154",
        "Port": 11210
      }
    ]
  }
}
```

**Comment by cnblogs-dudu** [comment]
Fixed in [EnyimMemcachedCore 2.1.0](https://www.nuget.org/packages/EnyimMemcachedCore/2.1.0)
