### ISSUE TITLE
BSON does not support unsigned values. 

### ISSUE THREAD

**Issue by Chang228** [cnblogs/EnyimMemcachedCore#28]
BSON does not support unsigned types, if the number larger than signed type max value, it throws exception:

> Value is too large to fit in a signed 32 bit integer. BSON does not support unsigned values.

**Comment by cnblogs-dudu** [comment]
Update to [EnyimMemcachedCore 2.1.0](https://www.nuget.org/packages/EnyimMemcachedCore/2.1.0) and use BinaryFormatterTranscoder.
```json
{
  "enyimMemcached": {
    "Transcoder": "BinaryFormatterTranscoder"
  }
}
```
