### ISSUE TITLE
Memcached Authentication Support

### ISSUE THREAD

**Issue by greggbjensen** [cnblogs/EnyimMemcachedCore#3]
For our project, we do require credentials to use Memcached.  Is there support for that?

Thanks,

Gregg

**Comment by greggbjensen** [comment]
I created a pull request that adds this support.
#4

**Comment by cnblogs-dudu** [comment]
Upload  a package to NuGet server for this. See https://www.nuget.org/packages/EnyimMemcachedCore/1.1.0.1

**Comment by greggbjensen** [comment]
Thanks, that was fast.
