### ISSUE TITLE
Cannot access socket pool configuration from appsettings?

### ISSUE THREAD

**Issue by rahulkushwaha12** [cnblogs/EnyimMemcachedCore#31]
I am not able to select the minpoolsize and maxpoolsize configuration from appsettings.json file.
I am always getting the default value.
Please help anyone?

**Comment by cnblogs-dudu** [comment]
Sorry. I am trying to fix it.

**Comment by cnblogs-dudu** [comment]
It will be fixed tomorrow.

**Comment by cnblogs-dudu** [comment]
Fixed in [EnyimMemcachedCore 2.0.4](https://www.nuget.org/packages/EnyimMemcachedCore/2.0.4)
