### ISSUE TITLE
Error during deserilization dictionary

### ISSUE THREAD

**Issue by sometime** [cnblogs/EnyimMemcachedCore#39]
I need to cache the dictionary

`var dict = new Dictionary<int, HashSet<int>>();`
`dict.Add(1, new HashSet<int> { 1, 2, 3 });`
`dict.Add(2, new HashSet<int> { 4, 5, 6 });`

`var key = "dict_key";`
`_cacheClient.Store(StoreMode.Set, key, dict);`
`var obj = _cacheClient.Get<Dictionary<int, HashSet<int>>>(key); <-- this error`

Error Message = "Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'System.Collections.Generic.Dictionary[System.Int32,System.Collections.Generic.HashSet[System.Int32]]' because the type requires a JSON object (e.g. {\"name\":\"value\"}) to deserialize...`

But Dictionary<TKey, TValue> is ISerializable.

**Comment by cnblogs-dudu** [comment]
Change to use BinaryFormatterTranscoder
``` json
{
  "enyimMemcached": {
    "Transcoder": "BinaryFormatterTranscoder"
  }
}
```

**Comment by sometime** [comment]
Works for me! Thank you!
