### ISSUE TITLE
Nuget package version error?

### ISSUE THREAD

**Issue by catcherwong** [cnblogs/EnyimMemcachedCore#49]
When I want to use **FlushAllAsync** in my code, this api should work in version **2.1.0.6** but I can not find this api via VS!

I use *Go To Definition* to see the interface `IMemcachedClient`, I also can not find out this api as well!

And I notice the summary which makes me confuse here!

![1](https://user-images.githubusercontent.com/8394988/38193070-adaeb7e2-36a2-11e8-9bf8-3dbddcddd2bc.png)

Is there something wrong about version 2.1.0.6 ?

**Comment by cnblogs-dudu** [comment]
Sorry! Fixed in 2.1.0.7. The reason it that `dotnet pack` did not rebuild project.

**Comment by catcherwong** [comment]
Thanks! It works now! 😄
