### ISSUE TITLE
Release 1.1.0 causes NullReferenceException in AddServer when running in AWS

### ISSUE THREAD

**Issue by sdaub** [cnblogs/EnyimMemcachedCore#5]
Upon upgrading to the latest release, 1.1.0 I am getting an exception when initializing memcached and adding a server. This code has been working without issue and the only change I made was updating this package.  Here is the code to setup Memcached which is causing the problem: 

                var memcachedClientLogger = _loggerFactory.CreateLogger&lt;MemcachedClient&gt;();
                var options = Options.Create(new MemcachedClientOptions());
                var config = new MemcachedClientConfiguration(memcachedClientLogger, options);
                foreach (var node in CacheNodes)
                {
                    Logger.Debug("Adding memcache server node {0}:{1} to configuration", node.Endpoint.Address,
                        node.Endpoint.Port);
                    config.AddServer(node.Endpoint.Address, node.Endpoint.Port);   //Line 83 in the stacktrace below
                }

I get NRE with this stack trace:
>System.NullReferenceException: Object reference not set to an instance of an object.    at Enyim.Caching.Configuration.ConfigurationHelper.ResolveToEndPoint(String host, Int32 port)    at Enyim.Caching.Configuration.MemcachedClientConfiguration.AddServer(String host, Int32 port)    at Foo.AWS.ElastiCache.ElastiCacheService.<Init>d__8.MoveNext() in /src/Foo.AWS/ElastiCache/ElasticCacheService.cs:line 83 --- End of stack trace from previous location where exception was thrown ---    .....

The logged message before calling AddServer is: 

> Adding memcache server node XXXXXX.uiezb6.0001.use1.cache.amazonaws.com:11211 to configuration 

This appears to be related to commit dc5cf834, which was the most recent change prior to releasing 1.1.0.

**Comment by cnblogs-dudu** [comment]
Sorry! Please upgrade to EnyimMemcachedCore 1.1.0.1 to fix it.

**Comment by sdaub** [comment]
That worked.  Thanks!  And thanks for a great library.
