### ISSUE TITLE
只能通过core mvc的依赖注入使用？我在普通类库怎么使用？

### ISSUE THREAD

**Issue by SayHelloXXXX** [cnblogs/EnyimMemcachedCore#60]
只能通过core mvc的依赖注入使用？我在普通类库怎么使用？

**Comment by ZeekoZhu** [comment]
可以手动 new 一个实例来用的，https://github.com/cnblogs/EnyimMemcachedCore/blob/dotnetcore/Enyim.Caching/MemcachedClient.cs

**Comment by cnblogs-dudu** [comment]
普通类库不用关心如何依赖注入，只需在构造函数中声明 IMemcachedClient 接口，类库的使用者会自己注入具体的依赖，你也可以提供 ServiceCollectionExtensions 帮助类库的使用者注入 IMemcachedClient 的依赖。

**Comment by echofool** [comment]
这个实现感觉略有不妥，强行依赖 asp dotnet core , 实际上我认为缓存就是缓存，不应该管这么多。要 support 特定环境的支持，可以单独拎出来。
