### ISSUE TITLE
MemcachedClient & MemcachedClientConfiguration 构造函数依赖ILoggerFactory

### ISSUE THREAD

**Issue by weitaolee** [cnblogs/EnyimMemcachedCore#84]
不建议构造函数依赖ILoggerFactory，支持ILoggerFactory是没问题的，不过没有ILoggerFactory就不能使用，这个不太合理。 建议支持不带ILoggerFactory的构造函数，保持和原Enyim构造函数的兼容性

**Comment by cnblogs-dudu** [comment]
You can pass `new LoggerFactory()` into constructor.

**Comment by weitaolee** [comment]
Thanks for feedback,dudu.  I just care the dependency not how to fix this problem.

**Comment by weitaolee** [comment]
Yeah,but you can use some code to solve it, for example
 `
 remain the constructor which include ILoggerFactory,and use some code like blow 
   if log is not  null
  {
    write log;
  }
  It's will not write any log  if someone use the constructor which not include ILoggerFactory(this's mean log is null)
`

**Comment by kt81** [comment]
@weitaolee 
There is an user-side solution that is to use `Microsoft.Extensions.Logging.Abstractions.NullLoggerFactory`.
I recommend you to use actual logger to check node pool's status, though.

**Comment by weitaolee** [comment]
@kt81  got it, thanks. this issue can be closed
