### ISSUE TITLE
How to use it with dotnet core console application?

### ISSUE THREAD

**Issue by gouhan** [cnblogs/EnyimMemcachedCore#94]
in the asp.net core application, i can be used with code below:
` services.AddEnyimMemcached();`

`app.UseEnyimMemcached();`

 how to make it work in console application?

**Comment by cnblogs-dudu** [comment]
Via Generic Host, See https://www.cnblogs.com/CoderAyu/p/9564977.html

**Comment by gouhan** [comment]
thanks
