### ISSUE TITLE
asp.net core程序启动后，有大量请求进来时，线程死锁

### ISSUE THREAD

**Issue by ZhiqiangTao** [cnblogs/EnyimMemcachedCore#98]
先上图片：
![image](https://user-images.githubusercontent.com/16182251/55846784-83af8780-5b79-11e9-8962-118873ecad66.png)

我的core api是跑在容器中的，偶尔有时候，docker run起来之后，整个api就hang住了，其他所有接口都无法响应。
然后我用lldb调试下，发现有个线程死锁了，跟进去一看，就是上面的图片。

因为这个问题在生产环境上很容易复现，生产环境并发量还是挺大的；但是这个问题在测试环境中从来没有复现过（没有请求量）。

我用的clinet版本为：
![image](https://user-images.githubusercontent.com/16182251/55846915-01739300-5b7a-11e9-9b35-ee2813d1bb31.png)

**Comment by cnblogs-dudu** [comment]
建议升级到最新版试试，我们在高并发生产环境中使用并未遇到这个问题

**Comment by ZeekoZhu** [comment]
这个问题确实存在，可以看这个简单的测试项目： https://github.com/timy07/EnyimMemcachedCoreTest

**Comment by cnblogs-dudu** [comment]
Sorry. This issue has been fixed in 2.2.0-beta5. Please try it.
